[general]
live_config_reload = true
import = [ "./nightfly-alacritty.toml" ]


[font]
size        = 15.0
normal      = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold        = { family = "FiraCode Nerd Font Mono", style = "Bold"    }
italic      = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold"    }
